# Generated by Django 2.1.1 on 2018-09-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.DateField(verbose_name='follow date')),
                ('report_time', models.TimeField(verbose_name='report time')),
                ('reported_on_time', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuency_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_name', models.CharField(max_length=20)),
                ('initial_time', models.TimeField(verbose_name='interval ini')),
                ('end_time', models.TimeField(verbose_name='Interval end')),
            ],
        ),
        migrations.CreateModel(
            name='IntradayFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intraday_frecuency_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=50)),
                ('report_format', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFollowUp.Account')),
                ('frequency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppFollowUp.IntradayFrequency')),
                ('interval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppFollowUp.Interval')),
                ('weekly_frecuency', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppFollowUp.Frequency')),
            ],
        ),
        migrations.AddField(
            model_name='followup',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFollowUp.Report'),
        ),
        migrations.AddField(
            model_name='followup',
            name='report_interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFollowUp.Interval'),
        ),
    ]
