# Generated by Django 2.1.1 on 2018-09-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFollowUp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=60)),
                ('received_date_time', models.DateTimeField(verbose_name='received date time')),
                ('sender', models.CharField(max_length=30)),
            ],
        ),
    ]
